# datastore charts values
mongodb:
  # false if wants to use external mongodb
  enabled: true
  auth:
    rootPassword: <<MongoPassword>>
    username: <<MongoUsername>>
    password: <<MongoPassword>>
    # create database manually if external
    database: nected
postgresql:
  # false if wants to use external postgresql
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: <<PostgresPassword>>
        # create username manually if external
        username: <<PostgresUserName>>
        password: <<PostgresPassword>>
        # create database manually if external
        database: nected
redis:
  # false if wants to use external redis
  enabled: true
elasticsearch:
  # false if wants to use external elastic
  enabled: false
  secret:
    password: <<ElasticUserPass>>

