# datastore charts values
postgresql:
  # false if wants to use external postgresql
  enabled: true
  image:
    registry: public.ecr.aws/f6k1n6r3
    repository: postgres
    tag: 16.2.0
    pullPolicy: IfNotPresent
  global:
    postgresql:
      auth:
        postgresPassword: psqlMainPass123
        # create username manually if external
        username: nected
        password: psqlPass123
        # create database manually if external
        database: nected
  primary:
    persistence:
      storageClass: "default"
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  volumePermissions:
    enabled: true
    image:
      registry: public.ecr.aws/f6k1n6r3
      repository: postgres
      tag: 12-os-shell
      digest: ""
      pullPolicy: IfNotPresent

redis:
  # false if wants to use external redis
  enabled: true
  image:
    registry: public.ecr.aws/f6k1n6r3
    repository: redis
    tag: 8.2.1
    pullPolicy: IfNotPresent
  master:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

elasticsearch:
  # false if wants to use external elastic
  enabled: true
  secret:
    password: esPass123
  volumeClaimTemplate:
    storageClassName: "default"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

