# datastore charts values
postgresql:
  # false if wants to use external postgresql
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: psqlMainPass123
        # create username manually if external
        username: nected
        password: psqlPass123
        # create database manually if external
        database: nected
  primary:
    persistence:
      storageClass: "default"
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
redis:
  # false if wants to use external redis
  enabled: true
  master:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
elasticsearch:
  # false if wants to use external elastic
  enabled: true
  secret:
    password: esPass123
  volumeClaimTemplate:
    storageClassName: "default"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

