replicaCount: 1

envVars:
  VITE_API_HOST: http://<<backend-nalanda-domain>>
  VITE_GRAPHQL_URL: http://<<backend-nalanda-domain>>/graphql/query
  VITE_EDITOR_URL: http://<<frontend-editor-domain>>
  VITE_NGINX_SERVER_NAME: <<frontend-konark-domain>>

ingress:
  enabled: true
  className: <<ingressClassName>> # azure: "azure-application-gateway", aws: "alb"
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: /
  hosts:
    - host: <<frontend-konark-domain>>
      paths:
          - path: /
            pathType: <<pathType>> # zzure: Exact, aws: Prefix