# editor chart values to be updated
editor:
  replicaCount: 1
  envVars:
    REACT_APP_ALLOWED_DOMAINS: <<scheme>>://<<ui-domain>>
    REACT_APP_SQL_LINT: <<scheme>>://<<backend-domain>>/misc/proxy/lint
    REACT_APP_EXECUTE_JS_API: <<scheme>>://<<backend-domain>>/integration/code/execute
    REACT_APP_NGINX_SERVER_NAME: <<editor-domain>>

  ingress:
    enabled: false
    className: <<ingressClassName>>
    hosts:
      - host: <<editor-domain>>
        paths:
            - path: /
              pathType: Prefix

# konark chart values to be updated
konark:
  replicaCount: 1
  envVars:
    VITE_API_HOST: <<scheme>>://<<backend-domain>>
    VITE_GRAPHQL_URL: <<scheme>>://<<backend-domain>>/graphql/query
    VITE_EDITOR_URL: <<scheme>>://<<editor-domain>>
    VITE_NGINX_SERVER_NAME: <<ui-domain>>

  ingress:
    enabled: false
    className: <<ingressClassName>>
    hosts:
      - host: <<ui-domain>>
        paths:
            - path: /
              pathType: Prefix

# nalanda chart values to be updated
nalanda:
  replicaCount: 1
  envVars:
    ALLOWED_CORS_ORIGIN: <<scheme>>://<<backend-domain>>,<<scheme>>://<<ui-domain>>,<<scheme>>://<<editor-domain>>
    # if external use external host address
    MASTER_DB_USER: nected
    MASTER_DB_PASSWORD: psqlPass123
    MASTER_DB_HOST: datastore-postgresql
    # if external use external host address
    REDIS_HOST: datastore-redis-master
    # enable elastic if installed using datastore or used external
    ELASTIC_ENABLED: true
    # if external use external host address
    ELASTIC_HOSTS: http://elasticsearch-master:9200
    ELASTIC_USER: elastic
    ELASTIC_PASSWORD: esPass123
    # aws ses credentials if EMAIL_PROVIDE: ses
    AWS_ACCESS_KEY:
    AWS_SECRET_KEY:
    AWS_REGION:
    # email
    SEND_EMAIL: false
    EMAIL_PROVIDER: smtp
    # email sender setting
    SENDER_EMAIL:
    SENDER_NAME:
    # smtp provider credentials
    EMAIL_INSECURE_TLS: true
    EMAIL_HOST:
    EMAIL_PORT: 587
    EMAIL_USERNAME:
    EMAIL_PASSWORD:
    ASSETS_BASE_URL: <<scheme>>://<<ui-domain>>/assets/konark
    KONARK_BASE_URL: <<scheme>>://<<ui-domain>>
    # comma separated email domains to allow signup from
    SIGNUP_DOMAINS:
    # sql-linter service url (change only if release name is not sql-linter)
    PROXY_SQL_LINT_URL: http://nected-sql-linter/api/v1/core/lint
    # default user created on setup
    NECTED_USER_EMAIL: user@example.com
    NECTED_USER_PASSWORD: userPassword123
    # default vidhaan settings
    DEFAULT_VIDHAAN_SCHEME: <<scheme>>
    DEFAULT_VIDHAAN_DOMAIN: <<router-domain>>
    # k8s cluster gw ip
    DEFAULT_VIDHAAN_WHITELISTED_IPS: 127.0.0.1
 
  ingress:
    enabled: false
    className: <<ingressClassName>>
  hosts:
    - host: <<backend-domain>>
      paths:
          - path: /
            pathType: Prefix

# vidhaan-executer chart to be updated
vidhaan-executer:
  replicaCount: 1
  envVars:
    REDIS_HOST: datastore-redis-master:6379
    # enable elastic if installed using datastore or used external
    ELASTIC_ENABLED: true
    AUDIT_LOG_ENABLED: true
    # if external use external host address
    ELASTIC_ADDRESSES: http://elasticsearch-master:9200
    # update if external and different user
    ELASTIC_USERNAME: elastic
    ELASTIC_PASSWORD: esPass123

# vidhaan-router chart to be updated
vidhaan-router:
  replicaCount: 1
  envVars:
    REDIS_HOST: datastore-redis-master:6379
    # enable elastic if installed using datastore or used external
    ELASTIC_ENABLED: true
    AUDIT_LOG_ENABLED: true
    # if external use external host address
    ELASTIC_ADDRESSES: http://elasticsearch-master:9200
    # update if external and different user
    ELASTIC_USERNAME: elastic
    ELASTIC_PASSWORD: esPass123

  ingress:
    enabled: false
    className: <<ingressClassName>>
    hosts:
      - host: <<router-domain>>
        paths:
            - path: /
              pathType: Prefix