###
nameOverride: "nected-temporal"
fullnameOverride: "nected-temporal"

server:
  enabled: true
  config:
    persistence:
      defaultStore: default
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          # if external use external host address & credentials
          host: datastore-postgresql
          port: 5432
          user: nected
          password: psqlPass123
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          # if external use external host address & credentials
          host: datastore-postgresql
          port: 5432
          user: nected
          password: psqlPass123
  frontend:
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  history:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 1048Mi
  matching:
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

admintools:
  enabled: false

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true

elasticsearch:
  # enable setup if elastic used external or datastore for temporal_visibility
  external: false
  # if external use external host address & credentials
  host: elasticsearch-master
  port: 9200
  username: elastic
  password: esPass123