###
nameOverride: "nected-temporal"
fullnameOverride: "nected-temporal"

NECTED_PG_HOST: &pgHost datastore-postgresql
NECTED_PG_USER: &pgUser nected
NECTED_PG_PASSWORD: &pgPassword psqlPass123
NECTED_PG_PORT: &pgPort 5432
NECTED_PG_TLS_ENABLED: &pgTlsEnabled false
NECTED_PG_HOST_VERIFICATIO: &pgHostVerification false

server:
  enabled: true
  dynamicConfig:
    matching.numTaskqueueReadPartitions:
    - value: 20
      constraints: {}
    matching.numTaskqueueWritePartitions:
    - value: 20
      constraints: {}
  config:
    logLevel: "debug,info"
    # IMPORTANT: This value cannot be changed, once it's set.
    numHistoryShards: 512
    dcRedirectionPolicy:
      policy: "selected-apis-forwarding"
      toDC: ""

    clusterMetadata:
      enableGlobalNamespace: true
      replicationConsumer:
        type: rpc
      failoverVersionIncrement: 100
      masterClusterName: "nected-op"
      currentClusterName: "nected-op" # <current cluster name>
      clusterInformation:
        nected-op:
          enabled: true
          initialFailoverVersion: 1
          rpcName: "frontend"
          rpcAddress: "0.0.0.0:7233"
    persistence:
      defaultStore: default
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          database: temporal
          maxConns: 20
          maxConnLifetime: "1h"
          # if external use external host address & credentials
          host: *pgHost
          port: *pgPort
          user: *pgUser
          password: *pgPassword
          tls:
           enabled: *pgTlsEnabled
           enableHostVerification: *pgHostVerification
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          database: temporal_visibility
          maxConns: 20
          maxConnLifetime: "1h"
          # if external use external host address & credentials
          host: *pgHost
          port: *pgPort
          user: *pgUser
          password: *pgPassword
          tls:
            enabled: *pgTlsEnabled
            enableHostVerification: *pgHostVerification
  frontend:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  history:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 500m
        memory: 1048Mi
  matching:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  worker:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

admintools:
  enabled: false
web:
  enabled: false

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true

elasticsearch:
  external: false
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
cassandra:
  enabled: false
mysql:
  enabled: false
