###
nameOverride: "nected-temporal"
fullnameOverride: "nected-temporal"

server:
  enabled: true
  dynamicConfig:
    matching.numTaskqueueReadPartitions:
    - value: 20
      constraints: {}
    matching.numTaskqueueWritePartitions:
    - value: 20
      constraints: {}
  config:
    logLevel: "debug,info"
    # IMPORTANT: This value cannot be changed, once it's set.
    numHistoryShards: 512
    dcRedirectionPolicy:
      policy: "selected-apis-forwarding"
      toDC: ""

    clusterMetadata:
      enableGlobalNamespace: true
      replicationConsumer:
        type: rpc
      failoverVersionIncrement: 100
      masterClusterName: "nected-op"
      currentClusterName: "nected-op" # <current cluster name>
      clusterInformation:
        nected-op:
          enabled: true
          initialFailoverVersion: 1
          rpcName: "frontend"
          rpcAddress: "0.0.0.0:7233"
    persistence:
      defaultStore: default
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          # if external use external host address & credentials
          host: datastore-postgresql
          port: 5432
          user: nected
          password: psqlPass123
          database: temporal
          # existingSecret: temporal-default-store
          maxConns: 20
          maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          # if external use external host address & credentials
          host: datastore-postgresql
          port: 5432
          user: nected
          database: temporal_visibility
          password: psqlPass123
          # existingSecret: temporal-default-store
          maxConns: 20
          maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
  frontend:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  history:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 500m
        memory: 1048Mi
  matching:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  worker:
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: "1"
      maxReplicas: "1"
      targetCPU: "75"
      targetMemory: "75"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

admintools:
  enabled: false
web:
  enabled: false

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true

elasticsearch:
  # disable if postgres is used for visibility
  external: false
  enabled: false
  # if external use external host address & credentials
  host: elasticsearch-master
  scheme: http
  port: 9200
  version: v7
  username: elastic
  password: esPass123
  visibilityIndex: "temporal_visibility_v1_op"
prometheus:
  enabled: false
grafana:
  enabled: false
cassandra:
  enabled: false
mysql:
  enabled: false
