replicaCount: 1

envVars:
  REDIS_HOST: "datastore-redis-master:6379"
  # vidhaan agen key, any uuid, should be same in nalanda / vidhaan-router / vidhaan-exdecuter
  VIDHAAN_AGENT_KEY: <<VidhaanSecretKey>>
  # license key is issued by Nected
  VIDHAAN_PRE_SHARED_KEY: <<LicenseKey>>
  # enable elastic if installed using datastore or used external
  ELASTIC_ENABLED: false
  AUDIT_LOG_ENABLED: false
  # if external use external host address
  ELASTIC_HOSTS: "http://elasticsearch-master:9200"
  # update if external and different user
  ELASTIC_USER: elastic
  ELASTIC_PASSWORD: <<ElasticUserPass>>
  # nalanda service url (change only if release name is not nalanda)
  NALANDA_BASE_URL: http://nalanda
  # nalanda service url (change only if release name is not temporal)
  TEMPORAL_EXECUTER_SERVER_HOST: nected-temporal-frontend:7233
