{{- if .Values.autoSetup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}-setup
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:    
    {{- include "common.autoSetupPodAnnotationsHook" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.autoSetup.backoffLimit }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}-setup
      labels:
          {{- include "common.labels" . | nindent 12 }}
    spec:
        containers:
            - name: setup
              image: {{ .Values.autoSetup.image.repository }}:{{ .Values.autoSetup.image.tag }}
              imagePullPolicy: {{ .Values.autoSetup.image.pullPolicy }}
              command: {{ .Values.autoSetup.command }}
              args: {{ .Values.autoSetup.args }}
            {{- with .Values.autoSetup.resources }}
              resources:
                {{- toYaml . | nindent 12 }}
            {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
              {{- toYaml . | nindent 12 }}
              {{- end }}
        {{- with .Values.volumes }}
        volumes:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        restartPolicy: OnFailure
{{- end}}