apiVersion: v2
description: Nected editor helm chart
home: https://github.com/nected/helm-charts
maintainers:
- email: devops@nected.ai
  name: Nected Devops
name: editor
sources:
- https://github.com/nected/nected-editor
appVersion: "op0.1.0-3"
type: application
version: 0.1.2

dependencies:
- name: common
  repository: https://charts.nected.io/
  tags:
  - nected-common
  version: 0.x.x
