---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nalanda
  namespace: default
  annotations:
    #kubernetes.io/ingress.class: azure/application-gateway
    #appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/health-probe-path: /health/ready
    #appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "name-of-my-root-cert1"
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: az-nalanda.dev.nected.io
    http:
      paths:
      - path: /
        backend:
          service:
            name: nalanda
            port:
              number: 80
        pathType: Exact