# Default values for nalanda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/f6k1n6r3/vidhaan
  pullPolicy: IfNotPresent
  tag: "op0.3.25"
  args: ["--executer"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# existingSecretMap:
#   - name: ENCRYPTKEY_EAR_1
#     valueFrom:
#       secretKeyRef:
#         name: encryption-at-rest-secret
#         key: encryption-at-rest
existingSecretMap: {}

envVars:
  ENVFILE_DEFAULT_VALUE: ""
  DEBUG: "false"
  DEPLOYMENT: production

  #Vidhaan
  VIDHAAN_AGENT_NAME: onpremise
  VIDHAAN_AGENT_KEY: afa8572b-facf-46ca-a40b-5cd23a3dbf02
  VIDHAAN_PRE_SHARED_KEY: 1182d659-8c9b-4541-90ac-8546372c326f

  #Router Config
  ALLOWED_HOSTS: "0.0.0.0"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8002"
  ASYNC_CONCURRENT_LIMIT: "10"
  REQUEST_PER_MINUTE_LIMIT: "1200"
  WEBHOOK_PER_MINUTE_LIMIT: "1200"
  MAX_REQUEST_SIZE: "3145728"
  ENABLE_PROFILING: "false"
  SKIP_LOG_PATHS: /health

  # Database
  DB_NAME: nected
  DB_USER: nected
  DB_PASSWORD: psqlPass123
  DB_HOST: datastore-postgresql
  DB_PORT: "5432"
  DB_LOG_MODE: "false"
  SSL_MODE: disable
  DB_CONNS_POOL_ENABLE: "true"
  DB_MAX_IDLE_CONNS: "2"
  DB_MAX_OPEN_CONNS: "10"
  DB_CONN_MAX_LIFE_TIME: 1h
  DB_CONN_MAX_IDLE_TIME: 1h

  # Redis Config
  REDIS_TLS_ENABLED: "false"
  REDIS_INSECURE_TLS: "true"
  REDIS_HOST: datastore-redis-master:6379
  REDIS_DATABASE: "1"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""

  # Elastic Config
  ELASTIC_PROVIDER: managed
  ELASTIC_ENABLED: "true"
  ELASTIC_INSECURE_TLS: "true"
  ELASTIC_SKIP_HEALTHCHECK: "false"
  ELASTIC_ADDRESSES: http://elasticsearch-master:9200
  ELASTIC_API_KEY: ""
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: esPass123

  # Audit log
  AUDIT_LOG_ENABLED: "true"
  AUDIT_LOG_INDEX: audit-all-vidhaan
  AWS_TRACE_ID_KEY: X-Amzn-Trace-Id
  X_FORWARDED_HEADER_KEY: X-Forwarded-For

  # Nalanda
  NALANDA_BASE_URL: http://nected-nalanda

  #Temporal For Executer Workers
  TEMPORAL_EXECUTER_SERVER_HOST: nected-temporal-frontend:7233
  TEMPORAL_EXECUTER_NAMESPACE: default
  TEMPORAL_EXECUTER_RETENTION_PERIOD: 24h
  TEMPORAL_EXECUTER_WORKFLOW_TASK_POLLERS: "2"
  TEMPORAL_EXECUTER_ACTIVITY_TASK_POLLERS: "2"
  TEMPORAL_EXECUTER_WORKFLOW_CONCURRENT_EXECUTION_SIZE: "1000"
  TEMPORAL_EXECUTER_ACTIVITY_CONCURRENT_EXECUTION_SIZE: "1000"
  TEMPORAL_EXECUTER_LOCAL_ACTIVITY_CONCURRENT_EXECUTION_SIZE: "1000"
  TEMPORAL_EXECUTER_ACTIVITY_EXECUTION_RPS: "100000"
  TEMPORAL_EXECUTER_LOCAL_ACTIVITY_EXECUTION_RPS: "100000"
  TEMPORAL_EXECUTER_INPUT_SIZE: "1783000"

  # Garuda runner
  GARUDA_SVC_HOST: "nected-garuda"
  GARUDA_SVC_PORT: "9090"
  GARUDA_BASE_URL: http://nected-garuda:9090

  # Sentry config
  SENTRY_DSN: ""
  SENTRY_ENABLED: "false"
  SENTRY_SAMPLING_RATE: "0.1"
  SENTRY_ENABLE_TRACING: "false"

  # Security
  SECURITY_ENABLED: "false"
  ENCRYPTION_KEY: EAR

  # Workflow config
  WORKFLOW_CONFIG_MAP: '{}'
  WORKFLOW_TIMEOUT_MAP: '{}'

  # Reporting
  ERROR_REPORTING_ENABLED: "false"
  ERROR_REPORTING_TTL: 24h

  # subdomains
  SKIP_SUBDOMAINS: "vidhaan.local"
  SKIP_SUBDOMAINS_WORKSPACE_IDS: "*"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoSetup:
  debug: false
  enabled: false
  image: {}
  command: []
  annotations: {}

service: {}

ingress:
  enabled: false
  className: 
  annotations: {}
  hosts: []
  tls: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1024Mi"

livenessProbe:
  exec:
    command:
    - sh
    - -c
    - |-
      kill -SIGUSR1 $(awk '{print $1}' /var/run/executer.pid)
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  exec:
    command:
    - sh
    - -c
    - |-
      kill -SIGUSR2 $(awk '{print $1}' /var/run/executer.pid)
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# additional volumes setting to mount configMap
mountConfigMap: false

nodeSelector: {}

tolerations: []

affinity: {}