# Default values for nalanda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/f6k1n6r3/nalanda
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "op0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envVars:
  # server config
  ALLOWED_CORS_ORIGIN: http://nalanda.local,http://konark.local,http://nected-editor.local
  ALLOWED_HOSTS: nalanda.local
  DEBUG: false
  DEPLOYMENT: production
  ENABLE_PROFILING: false
  SERVER_HOST: 0.0.0.0
  SERVER_PORT: 8001
  SERVER_TIMEZONE: UTC
  # secrets
  AES_SECRET: iAmAesKey
  SECRET: iAmSecret
    # Security
  SECURITY_ENABLED: true
  CHECK_ALLOWED_HOSTS: true
  # Database
  AUTO_MIGRATE: false
  MASTER_DB_NAME: nected
  MASTER_DB_USER: nected
  MASTER_DB_PASSWORD: nected
  MASTER_DB_HOST: datastore-postgresql
  MASTER_DB_PORT: 5432
  MASTER_DB_LOG_MODE: false
  MASTER_SSL_MODE: disable
  MASTER_DB_CONNS_POOL_ENABLE: true
  MASTER_DB_MAX_IDLE_CONNS: 5
  MASTER_DB_MAX_OPEN_CONNS: 10
  MASTER_DB_CONN_MAX_LIFETIME: 1h
  MASTER_DB_CONN_MAX_IDLE_TIME: 30m
  # mongoDB
  MONGO_DB_SCHEME: mongodb
  MONGO_DB_USER: nected
  MONGO_DB_PASSWORD: nected
  MONGO_DB_HOST: datastore-mongodb
  MONGO_DB_PORT: 27017
  MONGO_DB_LOCALE: "en"
  # Redis Config
  REDIS_HOST: datastore-redis-master
  REDIS_PORT: 6379
  REDIS_DATABASE: 0
  REDIS_PASSWORD: ""
  # Elastic Config
  ELASTIC_ENABLED: false
  ELASTIC_HOSTS: ""
  ELASTIC_API_KEY: ""
  ELASTIC_INSECURE_TLS: true
  # google
  GOOGLE_AUTH_ENABLED: false
  GOOGLE_CLIENT_ID: ""
  # aws ses
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_REGION: ""
  # email
  SEND_EMAIL: false
  EMAIL_PROVIDER: smtp
  SENDER_EMAIL: ""
  SENDER_NAME: ""
  EMAIL_INSECURE_TLS: ""
  EMAIL_HOST: ""
  EMAIL_PORT: ""
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
  # Recapcha config
  RECAPTCHA_ENABLED: false
  RECAPTCHA_SECRET: ""
  RECAPTCHA_VERIFY_URL: ""
  RECAPTCHA_MIN_SCORE: ""
  RECAPTCHA_CHECK_PATH: ""
  RECAPTCHA_CHECK_HOST: ""
  RECAPTCHA_CHECK_SCORE: ""
  # Sentry config
  SENTRY_DSN: ""
  SENTRY_ENABLED: false
  SENTRY_SAMPLING_RATE: 0.1
  SENTRY_ENABLE_TRACING: false
  # JWT
  JWT_ACCESS_TOKEN_EXP_TIME: 259200
  JWT_REFRESH_TOKEN_EXP_TIME: 1296000
  JWT_SECRET: iAmJWTSecret
  # konark
  ASSETS_BASE_URL: http://konark.local/assets/konark
  KONARK_BASE_URL: konark.local
  KONARK_EMAIL_VERIFICATION_PATH: /verify/signup/email/
  KONARK_OAUTH_REDIRECT_PATH: /oauth/redirect
  KONARK_RESET_PASSWORD_PATH: /reset-password/
  KONARK_WORKSPACE_INVITATION_PATH: /verify/workspace/invitation/
  # durations
  RESET_PASSWORD_EXP_TIME: 259200
  EMAIL_VERIFICATION_EXP_DURATION: 1296000
  WORKSPACE_INVITE_LINK_EXP_DURATION: 1296000
  RESET_PASSWORD_MAX_LIMIT: 3
  # features flags
  EXTERNAL_PERMISSION_URL: ""
  DEMO_CONNECTOR_TEMPLATE_ID: ""
  USECASE_VALUES_CONFIG_DOCUMENT_NAME: ""
  CONFIG_COLLECTION_NAME: config
  USECASE_DATABASE_NAME: ""
  SKIP_LOG_PATHS: /health/live,/health/ready
  CREATE_DEMO_ENTITIES_ENABLED: false
  WORKSPACE_SUBDOMAIN_ENABLED: false
  SIGNUP_DOMAINS:
  SYNC_PLUGINS: mysql,mongodb,postgres,sqlserver,redshift,restAPI
  # Audit log
  AWS_TRACE_ID_KEY: X-Amzn-Trace-Id
  ELASTIC_ADUIT_PATTERN: audit-*
  ELASTIC_ENTITY_AUDIT_INDEX: audit-log-nalanda
  ELASTIC_EVENT_LOG_INDEX: events-all-nalanda
  ELASTIC_TEMP_AUDIT_INDEX: audit-tmp-nalanda
  USAGE_INDEX_PATTERN: usage-*
  VIDHAAN_AUDIT_LOG_INDEX: audit-all-vidhaan
  X_FORWARDED_HEADER_KEY: X-Forwarded-For
  # proxy url
  CREDENTIAL_CONFIG_MAP: ""
  PROXY_SQL_LINT_URL: http://nected-sql-linter/api/v1/core/lint
  PROXY_RULE_URL: ""

  # Licensing Config
  LICENSE_DURATION: ""
  LICENSE_KEY_PATH: ""

  # Workflow config
  WORKFLOW_NOT_TESTABLE_NODE_TYPE: trigger,addNode,delayNode

  # nected user config
  NECTED_USER_EMAIL: ""
  NECTED_USER_PASSWORD: ""
  SUPER_ADMIN_USER_IDS: 1
  PRODUCT_WORKSPACE_ID: 1

  # usages
  FREE_PLAN_ID: 1
  IS_PAID: true
  RULE_LIMIT: 1000
  WORKFLOW_LIMIT: 500
  INVOCATION_LIMIT: 0
  EDITOR_LIMIT: 100

  # Vidhaan Config
  DEFAULT_VIDHAAN_SCHEME: http
  DEFAULT_VIDHAAN_DOMAIN: vidhaan.local
  DEFAULT_VIDHAAN_SECRET_KEY: afa8572b-facf-46ca-a40b-5cd23a3dbf02
  DEFAULT_VIDHAAN_WHITELISTED_IPS: ""
  VIDHAAN_INTERNAL_API_PATH: /nected/test
  VIDHAAN_EXTERNAL_API_PATH: /nected
  VIDHAAN_HEALTH_API_PATH: /nected/health
  VIDHAAN_EXECUTION_LOGS_API_PATH: /nected/execution-log
  VIDHAAN_SCHEDULE_API_PATH: /nected/schedule
  VIDHAAN_HEADER_AGENT_KEY_NAME: vidhaan-agent-key
  VIDHAAN_AUTH_HEADER_KEY_NAME: nected-api-key
  VIDHAAN_HEADER_WORKSPACE_KEY_NAME: vidhaan-workspace-key
  PRODUCT_API_KEY: ""


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoSetup:
  debug: true
  enabled: true
  image:
    repository: public.ecr.aws/f6k1n6r3/nalanda
    pullPolicy: IfNotPresent
    tag: "op0.1.0"
  command: ["/nalanda", "--init"]
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8001

ingress:
  enabled: true
  className: "alb"
  # classname for azure load balancer
  # className: "azure/application-gateway"
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "alb-name" # loadbalancer name
    # alb.ingress.kubernetes.io/ip-address-type: ipv4
    # alb.ingress.kubernetes.io/group.name: "alb-group-name"
    alb.ingress.kubernetes.io/healthcheck-path: /health/ready
    # alb.ingress.kubernetes.io/scheme: internet-facing 
    # alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/certificate-arn: "" # certificate ARN
    # alb.ingress.kubernetes.io/subnets: "" # public subnets "subnet-xxxxx,subnet-xxxxx"
    # annotations for azure load balancer
  hosts:
    - host: nalanda.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /health/live
    port: 8001
readinessProbe:
  httpGet:
    path: /health/live
    port: 8001

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: license-private-key
    secret:
      secretName: license-private-key
      items:
        - key: private.key
          path: private.key

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /tmp/license
    name: license-private-key
    readOnly: true
# additional volumes setting to mount configMap
mountConfigMap: true

nodeSelector: {}

tolerations: []

affinity: {}