apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  envFile: |
    {{- range $key, $value := .Values.envVars }}
    {{ $key }}={{ $value}}
    {{- end }}