temporal:
  nameOverride: "nected-temporal"
  fullnameOverride: "nected-temporal"

  server:
    enabled: true
    config:
      persistence:
        defaultStore: default
        default:
          driver: "sql"
          sql:
            driver: "postgres"
            host: datastore-postgresql
            port: 5432
            user: nected
            password: nected
            maxConns: 10
        visibility:
          driver: "sql"
          sql:
            driver: "postgres"
            host: datastore-postgresql
            port: 5432
            user: nected
            password: nected
            maxConns: 10
      clusterMetadata:
        masterClusterName: nectedOnPremise
        currentClusterName: nectedOnPremise
        clusterInformation:
          nectedOnPremise:
            enabled: true
            initialFailoverVersion: 1
            rpcName: "frontend"
            rpcAddress: "0.0.0.0:7233"
    frontend:
      replicaCount: 1
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
    history:
      replicaCount: 1
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 1000m
          memory: 2048Mi
    matching:
      replicaCount: 1
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
    worker:
      replicaCount: 1
      autoscaling:
        enabled: false
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
  admintools:
    enabled: false
  web:
    enabled: false
  schema:
    setup:
      enabled: true
    update:
      enabled: false
  elasticsearch:
    enabled: false
    external: false
    host: ""
    port: 9200
    username: "elastic"
    password: ""
    visibilityIndex: "temporal_visibility_v1_op"
  prometheus:
    enabled: false
  grafana:
    enabled: false
  cassandra:
    enabled: false
  mysql:
    enabled: false