# Default values for nalanda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: public.ecr.aws/f6k1n6r3/konark
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "op0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envVars:
  VITE_DEPLOYMENT_TYPE: onpremise
  VITE_ENVIRONMENT: production
  VITE_ENABLE_GOOGLE_LOGIN: false
  VITE_GOOGLE_CLIENT_ID: ""
  VITE_GA_MID: ""
  VITE_CLARITY_ID: ""
  VITE_GTM_ID: ""
  VITE_IP_INFO_KEY: ""
  VITE_RECAPTCHA_SITE_KEY: ""
  VITE_TANDC_URL: https://www.nected.ai/tnc
  VITE_PP_URL: https://www.nected.ai/privacy-policy
  VITE_COOKIE_CONSENT_ENABLED: false
  VITE_HIDE_OPTIONAL_ATTRIBUTES: true
  VITE_API_HOST: http://nalanda.local
  VITE_WITH_CREDENTIALS: false
  VITE_GRAPHQL_URL: http://nalanda.local/graphql/query
  VITE_AUTH_CONFIG_ENABLED: true
  VITE_ENABLE_EVENT_API: false
  VITE_SENTRY_DSN: ""
  VITE_RELEASE_TAG: ""
  VITE_API_FEATURE_FLAG: ""
  VITE_API_HOME_PAGE: ""
  VITE_API_STATE_UPDATE: ""
  VITE_API_GET_STATE: ""
  VITE_ADMIN_EMAIL_CONFIG: ""
  VITE_ASSETS_URL: /assets/konark/
  VITE_EDITOR_URL: http://nected-editor.local
  VITE_NGINX_SERVER_NAME: konark.local



serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoSetup:
  debug: false
  enabled: false
  image: {}
  command: []
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className:
  annotations: {}
  hosts:
    - host: konark.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# additional volumes setting to mount configMap
mountConfigMap: true

nodeSelector: {}

tolerations: []

affinity: {}