apiVersion: v2
name: datastore
description: helm charts to install data stores requred for Nected platform

home: https://nected.ai/

keywords:
  - Nected
  - Workflow automation
  - BRE, Business Rule Engine
  - Decision management platform
  - No-Code / Low-Code Rule Engine
  - No-Code / Low-Code Workflow automation

maintainers:
  - name: Socioverse Tech Private Ltd.
    url: https://nected.ai/

sources:
  - https://charts.nected.io

dependencies:
  - name: postgresql
    version: "15.2.2"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.0.2"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: "8.5.1"
    repository: https://charts.nected.io/
    condition: elasticsearch.enabled

type: application
version: 0.1.2
appVersion: "0.1.2"
