nameOverride: ""
fullnameOverride: ""

# Postgresql Chart Values
postgresql:
  enabled: true
  image:
    registry: public.ecr.aws/f6k1n6r3
    repository: postgres
    tag: 16.2.0
    pullPolicy: IfNotPresent
  global:
    postgresql:
      auth:
        postgresPassword: nected
        username: nected
        password: nected
        database: nected
  primary:
    persistence:
      enabled: true
      storageClass: "default"
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete
  volumePermissions:
    enabled: true
    image:
      registry: public.ecr.aws/f6k1n6r3
      repository: postgres
      tag: 12-os-shell
      digest: ""
      pullPolicy: IfNotPresent

# Redis Chart Values
redis:
  enabled: true
  image:
    registry: public.ecr.aws/f6k1n6r3
    repository: redis
    tag: 8.2.1
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    enabled: false
    sentinel: false
  master:
    count: 1
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"

# Elasticsearch Chart Values
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  secret:
    enabled: true
    password: nected
  protocol: http
  persistence:
    enabled: true
    labels:
      enabled: false
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "default"
    resources:
      requests:
        storage: 30Gi
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"