# Mongodb Chart Values
mongodb:
  enabled: true
  architecture: standalone
  useStatefulSet: true
  auth:
    enabled: true
    rootUser: root
    rootPassword: "7sdhT599nflY433"
    username: "nected"
    password: "Ne9ctg87$sdf8"
    database: "nected"
    
  persistence:
    enabled: true
    storageClass: "default"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Delete
  volumePermissions:
    enabled: true

# Postgresql Chart Values
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: "hdfh^sdgds$sdf"
        username: "nected"
        password: "NecTed#1234"
        database: "nected"
  primary:
    persistence:
      enabled: true
      storageClass: "default"
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete

  volumePermissions:
    enabled: true

# Redis Chart Values
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
    sentinel: false

  master:
    count: 1
    persistence:
      enabled: false

# Elasticsearch Chart Values
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  secret:
    enabled: true
    password: "asdkjhkj5h6j45rthjr"

  protocol: http
  persistence:
    enabled: true
    labels:
      enabled: false
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "default"
    resources:
      requests:
        storage: 30Gi

  networkPolicy:
    http:
      enabled: true