temporal:
  server:
    config:
      logLevel: "debug,info"

      numHistoryShards: 4096

      persistence:
        default:
          driver: "cassandra"

          cassandra:
            hosts: ["_host1_","_host2_","_host3_"]
            port: 9042
            keyspace: temporal
            user: ""
            password: ""
            existingSecret: ""
            replicationFactor: 3
            consistency:
              default:
                consistency: "local_quorum"
                serialConsistency: "local_serial"

        visibility:
          driver: "cassandra"

          cassandra:
            hosts: ["_host1_","_host2_","_host3_"]
            port: 9042
            keyspace: temporal_visibility
            user: "user"
            password: "password"
            existingSecret: ""
            replicationFactor: 3
            consistency:
              default:
                consistency: "local_quorum"
                serialConsistency: "local_serial"

  cassandra:
    enabled: false

  mysql:
    enabled: false

  postgresql:
    enabled: false

  schema:
    setup:
      enabled: false
    update:
      enabled: false
