{{- $staticCmap := include "nalanda.staticConfig" . }} 
{{- $defaultConfig := include "nalanda.defaultConfig" . }} 
{{- $envConfigMap := include "nalanda.configMap" . -}} 

{{- $finalCMap := include "common.tplvalues.merge" ( dict "values" ( list $envConfigMap $defaultConfig  $staticCmap ) "context" . ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nalanda.name" . }}
  labels:
    {{- include "nalanda.labels" . | nindent 4 }}
data:
    envFile: |
    {{- include "common.tplvalues.render" ( dict "value" $finalCMap "context" .) | nindent 4 }}