{{- if .Values.autoSetup.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}-setup
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.autoSetupPodAnnotationsHook" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.autoSetup.backoffLimit }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}-setup
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
        containers:
          - name: setup
            image: {{ .Values.autoSetup.image.repository }}:{{ .Values.autoSetup.image.tag }}
            imagePullPolicy: {{ .Values.autoSetup.image.pullPolicy }}
            {{- with .Values.autoSetup.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.autoSetup.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if not .Values.mountConfigMap }}
            envFrom:
            - configMapRef:
                name: {{ include "common.fullname" . }}
            {{- end }}
            {{- with .Values.autoSetup.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
              - mountPath: /mnt/temp
                name: {{ include "common.name" . }}-cm-volume
              {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 14 }}
              {{- end }}
        volumes:
          - name: {{ include "common.name" . }}-cm-volume
            configMap:
              name: {{ include "common.fullname" . }}
              items:
                - path: envFile
                  {{- if .Values.mountConfigMap }}
                  key: envFile
                  {{- else }}
                  key: ENVFILE_DEFAULT_VALUE
                  {{- end }}
          {{- if .Values.volumes }}
          {{- toYaml .Values.volumes| nindent 10 }}
          {{- end }}
        restartPolicy: OnFailure
{{- end}}