{{- if .Values.targetGroupBinding.enabled -}}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ include "common.fullname" . }}
    port: {{ .Values.service.port }}
  targetGroupARN: {{ required "targetGroupBinding.targetGroupARN is required when targetGroupBinding.enabled=true" .Values.targetGroupBinding.targetGroupARN | quote }}
  targetType: {{ .Values.targetGroupBinding.targetType | default "ip" }}
  {{- with .Values.targetGroupBinding.networking }}
  networking:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
