server:
  config:
    dcRedirectionPolicy:
      policy: "selected-apis-forwarding"
      toDC: ""

    clusterMetadata:
      enableGlobalNamespace: true
      replicationConsumer:
        type: rpc
      failoverVersionIncrement: 100
      masterClusterName: "nected-op"
      currentClusterName: "nected-op" # <current cluster name>
      clusterInformation:
        nected-op:
          enabled: true
          initialFailoverVersion: 1
          rpcName: "frontend"
          rpcAddress: "0.0.0.0:7233"
      #   cluster_a:
      #     enabled: true
      #     initialFailoverVersion: 1
      #     rpcName: "frontend"
      #     rpcAddress: "localhost:7233"
      #   cluster_b:
      #     enabled: true
      #     initialFailoverVersion: 2
      #     rpcName: "frontend"
      #     rpcAddress: "localhost:8233"
      #   cluster_c:
      #     enabled: false
      #     initialFailoverVersion: 3
      #     rpcName: "frontend"
      #     rpcAddress: "localhost:9233"
