apiVersion: v2
description: Nected sql-linter helm chart
home: https://github.com/nected/helm-charts
maintainers:
- email: devops@nected.ai
  name: Nected Devops
name: sql-linter
sources:
- https://github.com/nected/nected-sql-linter
appVersion: "op0.1.0"
type: application
version: 0.1.1

dependencies:
- name: common
  repository: https://charts.nected.io/
  tags:
  - nected-common
  version: 0.x.x
