---
replicas: 1
minimumMasterNodes: 1
secret:
  enabled: true
  password: "asdkjhkj5h6j45rthjr"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "default"
  persistentVolumeReclaimPolicy: Delete
  resources:
    requests:
      storage: 30Gi
