global:
  postgresql:
    auth:
      postgresPassword: "hdfh^sdgds$sdf"
      username: "nected"
      password: "NecTed#1234"
      database: "nected"
primary:
  persistence:
    enabled: true
    storageClass: "default"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Delete
volumePermissions:
  enabled: true