name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install YQ
        env:
          VERSION: v4.43.1
          BINARY: yq_linux_amd64
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
          tar xz && mv ${BINARY} /tmp/yq
      
      - name: Initialize custom helm repo (Helm V3 Bug)
        run: |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add nected https://charts.nected.io
            helm repo add lemontech https://charts.lemontech.engineering
            helm repo add incubator https://charts.helm.sh/incubator
            helm repo add prometheus https://prometheus-community.github.io/helm-charts
            helm repo add elastic https://helm.elastic.co
            helm repo add grafana https://grafana.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

